[general]
    port = "/dev/ttyUSB0"

[board]
    name = "optiboot_atmega328p"

    [board.reset]
    # The board automatically resets when attempting to flash
    automatic = true

    [board.avrdude]
    programmer = "arduino"
    partno = "atmega328p"
    baudrate = 115200
    do-chip-erase = true

    [board.usb-info]
    error = "Not able to guess port"
